#ifndef _FUNCONFIG_H
#define _FUNCONFIG_H

#define FUNCONF_SYSTEM_CORE_CLOCK 48000000  
#define CH32V003                      1
#define FUNCONF_USE_UARTPRINTF        0
#define FUNCONF_DEBUGPRINTF_TIMEOUT   0
#define FUNCONF_UART_PRINTF_BAUD      115200

#endif
